const $=s=>document.querySelector(s),K='glucopet:v1';
let S=Object.assign({target:50,log:[],best:0,water:{},profile:null},JSON.parse(localStorage.getItem(K)||'{}'));
const save=()=>localStorage.setItem(K,JSON.stringify(S)),day=()=>new Date().toISOString().slice(0,10);
const sugarToday=()=>S.log.filter(l=>l.d===day()).reduce((a,l)=>a+l.g,0),waterToday=()=>S.water[day()]||0,waterGoal=()=>S.profile?Math.round(S.profile.bb*29):2000,tsp=g=>+(g/4).toFixed(1);
const TABS=[['fakta','🏠','Faktapedia'],['kalk','🧮','Kalkulator'],['lens','📷','Gula Lens'],['kuli','🍴','Kuliner'],['game','🎮','Sugar Slash'],['air','💧','Hidrasi']];
let tab='fakta',kf='Semua',kq='',G=null,AC;
const FOOD=[['Tianlala','🧋','Boba Brown Sugar',38],['Chatime','🥛','Milk Tea Pearl',30],['Teazzi','🍑','Peach Tea',26],['Point Coffee','☕','Es Kopi Susu',24],['Kopi Kenangan','🫘','Kopi Kenangan Mantan',28],['Tomoro Coffee','🥥','Coconut Latte',22],['Mixue','🍦','Ice Cream Cone',18],['Momoyo','🍨','Soft Serve Sundae',24],['Roti O','🍞','Roti O Original',17],["D'Crepes",'🌯','Crepes Choco Banana',28],['Dubai Chewy Pistachio','🍫','Dubai Chewy Pistachio Kunafa',36],['Kaki Lima','🍧','Es Cendol',30],['Kaki Lima','🍌','Es Pisang Ijo',26],['Kaki Lima','🌽','Jasuke',14],['Kaki Lima','🟢','Klepon',18],['Kaki Lima','🥣','Kolak Pisang',24],['Kaki Lima','🧁','Kue Cubit',16],['Kaki Lima','🥮','Martabak Manis',42],['Air Putih','🚰','Air Putih / Air Mineral',0]];
const CAT=['Semua','Minuman & Kafe','Makanan & Snack','Kaki Lima & Tradisional'],cat=f=>['Tianlala','Chatime','Teazzi','Point Coffee','Kopi Kenangan','Tomoro Coffee','Mixue','Momoyo','Air Putih'].includes(f[0])?CAT[1]:f[0]==='Kaki Lima'?CAT[3]:CAT[2];
const MITOS=[['Gula aren/kelapa jauh lebih sehat dari gula pasir.','Tetap gula tambahan. Tubuh memprosesnya mirip, batas harian tetap berlaku.'],['Jus kemasan sama saja dengan buah potong.','Jus kemasan sering ditambah gula dan minim serat. Buah utuh diserap lebih lambat.'],['Pemanis nol kalori bebas diminum sepuasnya.','Kalorinya nol, tapi WHO tidak menyarankannya sebagai cara jangka panjang mengontrol berat badan.'],['Label "Less Sugar" berarti rendah gula.','Artinya hanya lebih sedikit dari versi biasanya. Cek angka gram di label.'],['Sugar crash cuma perasaan.','Gula darah yang melonjak lalu turun bisa bikin lemas, lapar, dan susah fokus.'],['Makan gula langsung bikin diabetes.','Risikonya naik lewat kelebihan kalori, berat badan naik, dan resistensi insulin jangka panjang.'],['Madu boleh sebebasnya.','WHO memasukkan madu ke gula bebas. Tetap dihitung dalam jatah harian.'],['Gula buah harus dibatasi seperti gula tambahan.','Batas WHO/Kemenkes untuk gula tambahan. Buah utuh punya serat, jadi lebih aman.'],['Minuman manis bikin kenyang.','Kalori cair kurang mengenyangkan, jadi mudah berlebihan.'],['Anak muda kebal gula.','AHA menyarankan remaja maksimal sekitar 25 g (6 sdt) gula tambahan per hari.'],['4 sdm gula sehari itu sedikit.','Batas Kemenkes 50 g. Satu boba bisa menghabiskan sebagian besar jatahmu.'],['Nggak manis berarti nggak ada gula.','Saus, roti, dan minuman tak manis bisa menyimpan gula tersembunyi. Baca label.']];
const HACK=[['💧 Minum air dingin, tunggu 10 menit','Rasa haus sering menyamar jadi ngidam. Banyak ngidam reda sendiri.'],['🪵 Substitusi kayu manis','Taburkan di teh atau kopi tanpa gula untuk aroma manis tanpa gula.'],['🥚 Serat/protein dulu, dessert belakangan','Memperlambat penyerapan gula sehingga lonjakannya lebih landai.'],['🚶 Jalan santai 10 menit setelah makan manis','Otot memakai glukosa darah, membantu meredam lonjakan.']];
const VS=[['Martabak Manis','🫓',42,'Martabak Telur','🍳',2],['Kopi Susu Kenangan Mantan','☕',28,'Americano','🫖',0],['Dubai Chewy Chocolate','🍫',36,'Dark Choc 75%','🌑',7],['Es Teh Jumbo Kaki Lima','🧊',35,'Es Teh Tawar Selasih','🍃',0]];
const LBL={'Sukrosa':['Gula pasir biasa (glukosa + fruktosa).','Cepat diserap, gula darah naik tajam.','Minuman manis, kue, permen.'],'Sirup Jagung HFCS':['Pemanis cair murah dari jagung.','Lonjakan gula darah cepat, mudah berlebihan karena murah dan manis.','Soda, minuman kemasan, saus.'],'Maltodekstrin':['Karbohidrat olahan dari pati.','Diserap sangat cepat, indeks glikemik tinggi walau tidak terasa manis.','Bubuk minuman, camilan, sereal.'],'Dekstrosa':['Nama lain glukosa murni.','Langsung masuk darah, lonjakan tajam.','Permen, roti, minuman olahraga.'],'Isomaltulosa':['Gula yang dicerna lebih lambat.','Lonjakan lebih landai dibanding sukrosa, tapi tetap gula dan tetap menyumbang kalori.','Minuman energi, formula nutrisi.']};
const GI=[['🧋','Boba Brown Sugar',1,8],['🍩','Donat Gula Salju',1,6],['🥥','Air Kelapa Murni',0,0],['🍵','Teh Tawar',0,0],['🍉','Buah Potong',0,0],['🍪','Biskuit Manis',1,4],['🥤','Soda Kaleng',1,9],['🍰','Cake Cokelat',1,7],['🥒','Timun',0,0],['🥚','Telur Rebus',0,0]];
const A={},V={},B={};
function head(){$('#today').textContent=`🍬 ${sugarToday()}/${S.target} g`}
function toast(t){const e=$('#toast');e.textContent=t;e.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>e.hidden=true,1800)}
function pop(t){const p=$('#pop');p.innerHTML=`<div>${t}<button class="btn" style="margin-top:12px;width:100%" data-a="close">Oke!</button></div>`;p.hidden=false}
function logIt(n,g){S.log.push({d:day(),n,g});save();head();toast(`${n} dicatat (${g} g)`)}
function render(){$('#nav').innerHTML=TABS.map(t=>`<button class="${t[0]===tab?'on':''}" data-a="go" data-v="${t[0]}"><span>${t[1]}</span>${t[2]}</button>`).join('');$('#view').innerHTML=V[tab]();B[tab]&&B[tab]();head();scrollTo(0,0)}
function go(t){stopGame();tab=t;render()}
document.addEventListener('click',e=>{const a=e.target.closest('[data-a]');if(a&&A[a.dataset.a])A[a.dataset.a](a)});
document.addEventListener('input',e=>{if(e.target.id==='kq'){kq=e.target.value.toLowerCase();$('#klist').innerHTML=klist()}});
A.go=a=>go(a.dataset.v);A.close=()=>$('#pop').hidden=true;A.flip=a=>a.classList.toggle('on');A.lbl=a=>{const l=LBL[a.dataset.v];pop(`<h3>${a.dataset.v}</h3><p><b>Apa itu:</b> ${l[0]}</p><p><b>Efek ke gula darah:</b> ${l[1]}</p><p><b>Contoh:</b> ${l[2]}</p>`)};
// FAKTAPEDIA
V.fakta=()=>`<section class="card hero"><svg class="cup" viewBox="0 0 100 120" aria-hidden="true"><path d="M20 30h60l-8 80H28z" fill="#fff" fill-opacity=".92"/><path d="M24 62h52l-4 48H28z" fill="#F9A8D4"/><rect x="14" y="22" width="72" height="10" rx="5" fill="#fff"/><path d="M58 22 66 2" stroke="#06B6D4" stroke-width="6" stroke-linecap="round"/><circle cx="40" cy="78" r="4" fill="#1E1B4B"/><circle cx="60" cy="78" r="4" fill="#1E1B4B"/><path d="M42 90q8 8 16 0" stroke="#1E1B4B" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="36" cy="102" r="4" fill="#4a2a5a"/><circle cx="50" cy="104" r="4" fill="#4a2a5a"/><circle cx="64" cy="102" r="4" fill="#4a2a5a"/><path d="M88 40l3 7 7 3-7 3-3 7-3-7-7-3 7-3z" fill="#FBBF24"/><path d="M8 60l2 5 5 2-5 2-2 5-2-5-5-2 5-2z" fill="#fff"/></svg><h1>Yakin Minuman Hits-mu Aman? 🧋 1 Boba Bikin Jatah Gula Seharian Ludes!</h1><div class="badges"><span>Kemenkes RI (Permenkes 30/2013): 50 g, maks. 4 sdm/hari</span><span>AHA remaja: 25 g (maks. 6 sdt/hari)</span><span>1 sdm = 12,5 g</span><span>1 sdt = 4 g</span><span>WHO: &lt;10% kalori</span></div><div class="row"><button class="btn" data-a="go" data-v="fakta" onclick="document.getElementById('fc').scrollIntoView({behavior:'smooth'})">✨ Jelajahi Faktapedia</button><button class="btn" data-a="go" data-v="game">🎮 Main Sugar Slash</button></div></section>
<section class="card" id="fc"><h2>Mitos vs Fakta</h2><p>Tap kartu untuk membalik.</p><div class="grid" style="margin-top:10px">${MITOS.map((m,i)=>`<div class="fc" data-a="flip"><div class="in"><div class="f front"><small>Mitos ${i+1}</small>${m[0]}</div><div class="f back"><small>Fakta</small>${m[1]}</div></div></div>`).join('')}</div><small class="src">Sumber: Kemenkes RI, WHO, AHA.</small></section>
<section class="card"><h2>Craving Hacks</h2>${HACK.map(h=>`<details><summary>${h[0]}</summary><p>${h[1]}</p></details>`).join('')}</section>
<section class="card"><h2>Versus Gula</h2>${VS.map(v=>`<div class="vs"><div class="bad">${v[1]}<br>${v[0]}<b>${v[2]} g</b></div><span>VS</span><div class="ok">${v[4]}<br>${v[3]}<b>${v[5]} g</b></div></div>`).join('')}<small class="src">Angka estimasi per porsi umum.</small></section>
<section class="card"><h2>Detektif Label Kemasan</h2><p>Komposisi ditulis dari bahan terbanyak. Makin awal gula muncul, makin banyak kandungannya. Tap bahan:</p><div class="res" style="font-size:12px"><b>Komposisi:</b> air, <span class="lb" style="display:inline-flex">${Object.keys(LBL).map(k=>`<button data-a="lbl" data-v="${k}">${k}</button>`).join('')}</span></div></section>`;
// KALKULATOR
V.kalk=()=>{const p=S.profile||{};const L=S.log.filter(l=>l.d===day());return `<section class="card"><h2>Kalkulator Batas Gula</h2><label>Tinggi badan (cm)</label><input id="tb" type="number" value="${p.tb||''}"><label>Berat badan (kg)</label><input id="bb" type="number" value="${p.bb||''}"><label>Usia</label><input id="us" type="number" value="${p.u||''}"><label>Gender</label><select id="gd"><option value="m" ${p.g==='m'?'selected':''}>Laki-laki</option><option value="f" ${p.g==='f'?'selected':''}>Perempuan</option></select><label>Level aktivitas</label><select id="ak">${[['1.2','Jarang olahraga'],['1.375','Ringan (1-3x/minggu)'],['1.55','Sedang (3-5x/minggu)'],['1.725','Berat (6-7x/minggu)']].map(o=>`<option value="${o[0]}" ${p.act==o[0]?'selected':''}>${o[1]}</option>`).join('')}</select><button class="btn" style="width:100%;margin-top:12px" data-a="calc">Hitung</button><div id="kres">${p.limit?kres(p):''}</div></section><section class="card"><h2>Jurnal Hari Ini</h2>${L.length?L.map((l,i)=>`<div class="item"><div class="grow"><b>${l.n}</b><small>${l.g} g gula</small></div><button class="mini" data-a="del" data-i="${S.log.indexOf(l)}">Hapus</button></div>`).join('')+`<p style="margin-top:8px"><b>Total: ${sugarToday()} g</b> dari target ${S.target} g</p>`:'<p>Belum ada catatan. Tambah dari Kuliner atau Gula Lens.</p>'}</section>`};
const kres=p=>`<div class="res"><p>BMR: <b>${Math.round(p.bmr)} kkal</b> | TEE: <b>${Math.round(p.tee)} kkal</b></p><p>Batas gula aman (10% kalori):</p><b class="n">${Math.round(p.limit)} g = ${tsp(p.limit)} sdt</b><button class="btn" style="width:100%;margin-top:10px" data-a="apply">Simpan Target Harian</button></div>`;
A.calc=()=>{const tb=+$('#tb').value,bb=+$('#bb').value,u=+$('#us').value,g=$('#gd').value,act=+$('#ak').value;if(!tb||!bb||!u)return toast('Isi tinggi, berat, dan usia dulu');const bmr=10*bb+6.25*tb-5*u+(g==='m'?5:-161),tee=bmr*act;S.profile={tb,bb,u,g,act,bmr,tee,limit:tee*.1/4};save();$('#kres').innerHTML=kres(S.profile)};
A.apply=()=>{S.target=Math.round(S.profile.limit);save();head();toast(`Target harian: ${S.target} g`)};A.del=a=>{S.log.splice(+a.dataset.i,1);save();render()};
// GULA LENS
V.lens=()=>`<section class="card"><h2>Gula Lens 📷</h2><p>Foto makanan/minumanmu dari kamera atau galeri.</p><input id="pic" type="file" accept="image/*" capture="environment" style="margin-top:8px"><div id="lres"></div><small class="src">Ini simulasi, bukan pengenalan gambar sungguhan. Cocokkan pilihan di bawah foto agar hasilnya akurat.</small></section>`;
B.lens=()=>{$('#pic').onchange=e=>{const f=e.target.files[0];if(!f)return;const water=/air|water|aqua|mineral|botol|tumbler/i.test(f.name);const guess=water?FOOD.length-1:Math.floor(Math.random()*(FOOD.length-1));$('#lres').innerHTML=`<img src="${URL.createObjectURL(f)}" alt="Foto" style="width:100%;border-radius:16px;margin-top:10px;max-height:220px;object-fit:cover"><label>Terdeteksi sebagai</label><select id="ls">${FOOD.map((x,i)=>`<option value="${i}" ${i===guess?'selected':''}>${x[1]} ${x[2]}</option>`).join('')}</select><button class="btn" style="width:100%;margin-top:10px" data-a="lens">Analisis</button><div id="lout"></div>`}};
A.lens=()=>{const f=FOOD[+$('#ls').value],g=f[3];$('#lout').innerHTML=`<div class="res"><span style="font-size:40px">${f[1]}</span> <b>${f[2]}</b><span class="dot" style="background:${g<=5?'#6EE7B7':g<=15?'#FDE68A':'#FCA5A5'}">${g<=5?'Hijau':g<=15?'Kuning':'Merah'}</span><p>Kadar gula: <b class="n">${g} gram</b></p><p>Kalori: <b>${g*4} kkal</b> | Setara <b>${tsp(g)} sdt</b></p>${g===0?'<p>100% Bebas Gula & Paling Sehat untuk Ginjal 💧</p>':''}<button class="btn" style="width:100%;margin-top:8px" data-a="log" data-i="${FOOD.indexOf(f)}">+ Masukkan ke Jurnal</button></div>`};
// KULINER
const klist=()=>FOOD.map((f,i)=>({f,i})).filter(({f})=>(kf==='Semua'||cat(f)===kf)&&(f[2]+f[0]).toLowerCase().includes(kq)).map(({f,i})=>{const k=f[3]*4;return `<div class="item"><span class="em">${f[1]}</span><div class="grow"><b>${f[2]}</b><small>${f[0]} | ${f[3]} g gula (${tsp(f[3])} sdt)</small><small>Bakar dengan: 🚶 ${Math.round(k/4)} mnt, 🏃 ${Math.round(k/10)} mnt, 🚴 ${Math.round(k/7)} mnt</small></div><button class="mini" data-a="log" data-i="${i}">+ Catat</button></div>`}).join('')||'<p>Tidak ada hasil.</p>';
V.kuli=()=>`<section class="card"><h2>Kuliner & Tenant Mall</h2><input id="kq" placeholder="Cari menu atau tenant..." value="${kq}"><div class="tens" style="margin-top:8px">${CAT.map(t=>`<button class="${t===kf?'on':''}" data-a="kf" data-v="${t}">${t}</button>`).join('')}</div><div id="klist">${klist()}</div><small class="src">Gula dan waktu bakar adalah estimasi (jalan 4, lari 10, sepeda 7 kkal/menit).</small></section>`;
A.kf=a=>{kf=a.dataset.v;render()};A.log=a=>{const f=FOOD[+a.dataset.i];logIt(f[2],f[3])};
// SUGAR SLASH
V.game=()=>`<section class="card"><h2>Sugar Slash: Smart Pick ⚡</h2><p>Geser kiri/tap SLASH untuk makanan tinggi gula, geser kanan/tap COLLECT untuk yang sehat dan rendah gula. 30 detik!</p><div id="stage"><p style="margin:10px 0">Rekor: <b>${S.best}</b></p><button class="btn" style="width:100%" data-a="gstart">Mulai</button></div></section>`;
function stopGame(){if(G){clearInterval(G.t);G=null}}
function beep(ok){try{AC=AC||new(window.AudioContext||window.webkitAudioContext)();const o=AC.createOscillator(),g=AC.createGain(),t=AC.currentTime;o.connect(g);g.connect(AC.destination);o.type=ok?'triangle':'sawtooth';o.frequency.setValueAtTime(ok?660:180,t);if(ok)o.frequency.exponentialRampToValueAtTime(990,t+.12);g.gain.setValueAtTime(.12,t);g.gain.exponentialRampToValueAtTime(.001,t+.18);o.start();o.stop(t+.2)}catch(e){}}
const gnext=()=>{G.cur=GI[Math.floor(Math.random()*GI.length)]},gcard=()=>{$('#gcard').innerHTML=`<span class="big">${G.cur[0]}</span><b>${G.cur[1]}</b>`},hud=g=>{$('#hud').innerHTML=`<span>⏱ ${g.left}s</span><span>⭐ ${g.s}</span><span>🔥 x${g.c}</span>`};
A.gstart=()=>{stopGame();G={s:0,c:0,left:30,last:null};gnext();$('#stage').innerHTML=`<div class="hud" id="hud"></div><div id="gcard" class="gcard"></div><div class="row"><button class="btn pink" data-a="gans" data-v="1">⚡ SLASH!</button><button class="btn green" data-a="gans" data-v="0">💚 COLLECT!</button></div>`;gcard();hud(G);const c=$('#gcard');let x0=null;c.onpointerdown=e=>{x0=e.clientX};c.onpointerup=e=>{if(x0===null)return;const d=e.clientX-x0;x0=null;if(d<-50)ans(true);else if(d>50)ans(false)};G.t=setInterval(()=>{G.left--;hud(G);if(G.left<=0)gend()},1000)};
A.gans=a=>ans(a.dataset.v==='1');
function ans(copet){if(!G)return;const ok=copet===!!G.cur[2];if(ok){G.c++;G.s+=10+Math.min(G.c,10)*2;if(copet)G.last=G.cur}else{G.c=0;G.s=Math.max(0,G.s-5)}beep(ok);gnext();gcard();hud(G)}
function gend(){const g=G;stopGame();if(g.s>S.best){S.best=g.s;save()}const t=g.s>=200?'Master Smart Pick ⚡':g.s>=120?'Sugar Slayer 😎':g.s>=50?'Pemburu Sehat 🍃':'Korban Boba Manja 🧋';const tr=g.last?`Tahukah kamu? ${g.last[1]} yang barusan kamu slash punya gula setara ${g.last[3]} sendok teh!`:'Tahukah kamu? Satu kaleng soda bisa mengandung gula setara 9 sendok teh.';$('#stage').innerHTML=`<h3>${t}</h3><p>Skor <b>${g.s}</b> | Rekor <b>${S.best}</b></p><div class="res">${tr}</div><button class="btn" style="width:100%;margin-top:10px" data-a="gstart">Main lagi</button>`}
// HIDRASI
V.air=()=>{const goal=waterGoal();return `<section class="card"><h2>Water Tracker 💧</h2><div class="bottle"><div class="fill" id="fill"></div><b id="wtxt">${waterToday()} / ${goal} ml</b></div><div class="grid">${[[200,'🥛 Gelas Kecil'],[350,'🥤 Gelas Sedang'],[600,'🍶 Tumbler Besar'],[1000,'🧴 Botol Jumbo']].map(w=>`<button class="btn" data-a="wadd" data-v="${w[0]}">+${w[0]} ml<br><small>${w[1]}</small></button>`).join('')}</div><button class="mini" style="margin-top:10px" data-a="wreset">Reset hari ini</button><div class="res" style="margin-top:12px">Air putih membantu ginjal membuang kelebihan glukosa lewat urine. Target: ${S.profile?'berat badanmu x 29 ml':'2000 ml (hitung di Kalkulator untuk target personal)'}.</div></section>`};
const wup=()=>{const m=waterToday();$('#fill').style.height=Math.min(100,m/waterGoal()*100)+'%';$('#wtxt').textContent=`${m} / ${waterGoal()} ml`};
B.air=()=>requestAnimationFrame(()=>requestAnimationFrame(wup));
A.wadd=a=>{S.water[day()]=waterToday()+ +a.dataset.v;save();wup();if(waterToday()>=waterGoal())toast('Target hidrasi tercapai! 🎉')};A.wreset=()=>{S.water[day()]=0;save();wup()};
render();
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));
